### ISSUE TITLE
Not compatible with liu haiping

### ISSUE THREAD

**Issue by csjiabin** [g123k/flutter-screen-theme-plugin#2]
`
enableDarkStatusBar() async {
    await ScreenTheme.darkStatusBar();
    bool hasLightStatusBar = await ScreenTheme.hasALightStatusBar();
    print(hasLightStatusBar);
  }
`

```
Unhandled exception:
MissingPluginException(No implementation found for method changeStatusBarTheme on channel g123k/screentheme)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:278:7)
<asynchronous suspension>
#1      ScreenTheme.darkStatusBar (package:screentheme/screentheme.dart:33:31)
<asynchronous suspension>
#2      TaskPageState.enableDarkStatusBar (file:///Users/csjiabin/hnl_delivery/lib/pages/TaskPage.dart:84:23)
<asynchronous suspension>
#3      TaskPageState.build.<anonymous closure>.<anonymous closure> (file:///Users/csjiabin/hnl_delivery/lib/pages/TaskPage.dart:132:29)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:494:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:549:30)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/t<…
```

**Comment by g123k** [comment]
Hello,

Thanks for your report.
On which device is the bug happening? Could you also post your `flutter doctor` output please?
